## GOAL

# request == 1 -> pickObject
# request == 2 -> placeObject
int32 request

# id that must be picked
int32 id

# Output from Detection.srv
apriltag_ros/AprilTagDetection[] detections
---
## RESULT

bool objectPicked
bool objectPlaced
---
## FEEDBACK

int32 status
